import marimo

app = marimo.App(width="full")


@app.cell
def _():
    import http.server
    import pathlib
    import threading
    from functools import partial

    import cql2
    import marimo as mo
    import pystac
    return cql2, http, mo, partial, pathlib, pystac, threading


@app.cell
def _(mo):
    catalogs = {"IDR samples (extended)": "catalogs/extended", "NGFF challenge (BIA)": "catalogs/challenge"}
    which = mo.ui.dropdown(catalogs, value="IDR samples (extended)", label="Catalog")
    which
    return (which,)


@app.cell
def _(mo, pathlib, pystac, which):
    catalog = pystac.Catalog.from_file(f"{which.value}/catalog.json")
    base = pathlib.Path(catalog.self_href).parent
    collections = [
        pystac.Collection.from_file(str(base / link.href))
        for link in catalog.get_links("child")
        if (base / link.href).exists()
    ]
    items = [item for collection in collections for item in collection.get_items(recursive=True)]
    mo.md(f"# {catalog.id}\n{catalog.description}\n\n**{len(items)}** items in **{len(collections)}** collections")
    return collections, items


@app.cell
def _(collections, mo):
    # Collection summaries (generated by pystac's built-in Summarizer) describe the ome:* keys
    # without opening a single item: value lists for categories, min/max ranges for sizes.
    def fmt(v):
        return f"{v['minimum']}–{v['maximum']}" if isinstance(v, dict) else ", ".join(map(str, v))

    keys = sorted({k for c in collections for k in c.summaries.to_dict()})
    mo.vstack([
        mo.md("## Collection summaries"),
        mo.ui.table(
            [{"key": k, **{c.id: fmt(c.summaries.to_dict().get(k, [])) for c in collections}} for k in keys],
            selection=None,
            pagination=False,
        ),
    ])
    return


@app.cell
def _(mo, which):
    # CQL2 is the STAC API filter language; the same text works against any STAC API with the Filter extension
    examples = {
        "Human samples": "\"bioimage:organism.term_id\" = 'NCBITaxon:9606'",
        "Electron microscopy": "\"bioimage:imaging_method.term_label\" LIKE '%electron%'",
        "Deep stacks (Z > 100)": "\"bioimage:size_z\" > 100",
    } if "challenge" in which.value else {
        "3D time-lapse with labels": "\"ome:size_z\" > 1 AND \"ome:size_t\" > 1 AND \"ome:has_labels\" = true",
        "Many channels (≥ 6)": "\"ome:size_c\" >= 6",
        "HCS plates": "\"ome:plate\" = true",
        "idr0062, NGFF 0.5": "\"idr:study\" = 'idr0062' AND \"ome:version\" = '0.5'",
        "Public domain": "license = 'CC0-1.0'",
        "Big 2D (X > 10000)": "\"ome:size_x\" > 10000 AND \"ome:size_z\" = 1",
    }
    example = mo.ui.dropdown(examples, value=list(examples)[0], label="Example query")
    example
    return (example,)


@app.cell
def _(example, mo):
    query = mo.ui.text_area(value=example.value, label="CQL2 filter", full_width=True)
    query
    return (query,)


@app.cell
def _(cql2, items, mo, query):
    expr = cql2.Expr(query.value)

    def matches(item):
        try:
            return expr.matches(item.to_dict())
        except Exception:
            # ponytail: cql2 raises when a compared property is null (e.g. no T axis); treat as no match
            return False

    hits = [i for i in items if matches(i)]
    mo.accordion({"CQL2-JSON (what a STAC API /search POST body would carry)": mo.json(expr.to_json())})
    return (hits,)


@app.cell
def _(hits, mo):
    def card(item):
        p = item.properties
        data = item.assets["data"].href
        meta = item.assets.get("metadata") or item.assets.get("ro-crate")
        # either extension: bioimage:size_x … or ome:size_x …
        sizes = {d: p.get(f"bioimage:size_{d.lower()}") or p.get(f"ome:size_{d.lower()}") for d in "XYZCT"}
        dims = " × ".join(f"{d}{sizes[d]}" for d in "XYZCT" if sizes.get(d))
        thumbnail = item.assets.get("thumbnail")
        preview = (f'<img src="{thumbnail.href}" width="96">' if thumbnail
                   else '<div style="width:96px;height:96px;background:#eee;font-size:10px">open in Vizarr</div>')
        return mo.Html(
            f'<a href="https://hms-dbmi.github.io/vizarr/?source={data}" target="_blank">{preview}</a>'
            f'<div style="font-size:11px;width:140px;word-break:break-all">{item.id}<br>{dims}<br>{p.get("license", "")}'
            + (" · labels" if p.get("ome:has_labels") else "")
            + (f' · <a href="{meta.href}" target="_blank">{meta.title or "metadata"}</a>' if meta else "")
            + "</div>"
        )

    mo.vstack([mo.md(f"**{len(hits)}** matches"), mo.hstack([card(i) for i in hits], wrap=True, justify="start")])
    return


@app.cell
def _(http, mo, partial, pathlib, pystac, threading, which):
    class CORS(http.server.SimpleHTTPRequestHandler):
        def end_headers(self):
            self.send_header("Access-Control-Allow-Origin", "*")
            super().end_headers()

    try:
        server = http.server.ThreadingHTTPServer(("localhost", 8000), partial(CORS, directory="."))
        threading.Thread(target=server.serve_forever, daemon=True).start()
    except OSError:
        pass  # already serving (cell re-run or 02_browse.py running)

    browse = pathlib.Path(f"{which.value}/catalog.json")
    catalog = pystac.Catalog.from_file(str(browse))
    children = [browse.parent / link.href for link in catalog.get_links("child")]
    if any(not child.exists() for child in children):
        browse = next((child for child in children if child.exists()), browse)
    url = f"https://radiantearth.github.io/stac-browser/#/external/http://localhost:8000/{browse.as_posix()}"
    mo.md(f"## STAC Browser\n[Open the extended catalog in STAC Browser]({url}): collections, summaries, ome:* properties, assets.")
    return


if __name__ == "__main__":
    app.run()
